# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ipv4_address 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "ipv4_address"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Nowicki"]
  s.date = "2013-11-15"
  s.description = "Recognize ipv4 addresses in many ways"
  s.email = "pr0d1r2@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".ruby-version",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ipv4_address.gemspec",
    "lib/ipv4_address.rb",
    "spec/ipv4_address_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Pr0d1r2/ipv4_address"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.5"
  s.summary = "Recognition of ipv4 addresses"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

